#!/bin/sh

#default values
URL=""
TITLE=""

#helper functions
output_help() {
cat <<EOF
ytpl-inv is a script to extract youtube playlists data to a json format
that can be imported on Invidious.

usage:

  ytpl-inv [playlist-url] -t "<playlist-title>"

EOF
}

output_version() {
cat <<EOF

ytpl-inv 1.0

License GPLv3: GNU GPL version 3.
This is free software: you are free to change and redistribute it.
developed by Paulo Neto

<https://www.github.com/paulobtn/ytpl-inv
EOF
}

[ "$#" -eq "0" ] && output_help && exit 0

#parsing the arguments
while [ "$#" -gt "0" ]; do
    case "$1" in
        "-t") TITLE="$2" && shift ;;
        "-h") output_help && exit 0 ;;
        "-v") output_version && exit 0 ;;
        *)
            if [ -n "`echo "$1" | grep "^-"`" ] || [ ! -z "$URL" ] ; then
                echo "invalid command. Use ytpl -h for help" >&2; exit 1
            else
                URL="$1"
            fi
        ;;
    esac
    if [ -n "$1" ]; then 
      shift
    fi
done

if [ -n "$URL" ]; then
  VIDEO_IDS=`youtube-dl -j --flat-playlist "$URL" | jq -r ".id" | sed 's/.*/"&"/'`
  VIDEO_IDS=`echo $VIDEO_IDS | sed 's/ /,/g'`
  VIDEO_IDS="{\"playlists\":[{\"title\":\"$(echo $TITLE)\",\"description\":\"\",\"privacy\":\"Public\",\"videos\":[$(echo $VIDEO_IDS)]}]}"
  echo $VIDEO_IDS
fi
